name: Build SSHelter

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: runtimeZip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/sshelter.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
